# Generated by Django 5.0.6 on 2026-06-02 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("marketplace", "0002_seed_default_categories"),
    ]

    operations = [
        migrations.AddField(
            model_name="servicecategory",
            name="user_suggested",
            field=models.BooleanField(
                default=False,
                help_text="Created by a user when listing a service; review name/slug in admin.",
            ),
        ),
    ]
