# Generated by Django 3.0.14 on 2022-07-15 12:30

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('route', models.CharField(max_length=100)),
                ('type_of_day', models.CharField(max_length=100)),
                ('information', jsonfield.fields.JSONField()),
                ('stops', models.ManyToManyField(to='app.Stop')),
            ],
        ),
    ]
