# Generated by Django 3.0.14 on 2022-07-15 12:48

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20220715_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='information',
            field=jsonfield.fields.JSONField(null=True),
        ),
    ]
