# Generated by Django 3.0.14 on 2022-07-28 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20220715_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='disabled',
            field=models.BooleanField(default=False),
        ),
    ]
