# Generated by Django 3.0.14 on 2022-10-02 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_stat'),
    ]

    operations = [
        migrations.AddField(
            model_name='stat',
            name='platform',
            field=models.CharField(default='NA', max_length=100),
            preserve_default=False,
        ),
    ]
