# Generated by Django 3.0.14 on 2022-10-02 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_stat_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='stat',
            name='language',
            field=models.CharField(default='NA', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stat',
            name='time',
            field=models.CharField(default='NA', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='stat',
            name='type_of_day',
            field=models.CharField(default='NA', max_length=100),
            preserve_default=False,
        ),
    ]
