# Generated by Django 3.0.14 on 2022-10-05 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20221002_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stat',
            name='timestamp',
            field=models.DateTimeField(),
        ),
    ]
