# Generated by Django 3.0.14 on 2023-07-14 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='stops',
            field=models.CharField(max_length=500),
        ),
    ]
