# Generated by Django 3.0.14 on 2023-07-15 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_auto_20230714_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='action',
            field=models.CharField(blank=True, choices=[('open', 'Open URL'), ('directions', 'Get Directions To'), ('call', 'Call To Number'), ('sms', 'Send SMS'), ('email', 'Send Email'), ('whatsapp', 'Send WhatsApp Message')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='ad',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('inactive', 'Inactive'), ('failed', 'Failed'), ('default', 'Default')], default='pending', max_length=100),
        ),
    ]
