# Generated by Django 3.2.8 on 2024-05-22 19:35

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_auto_20240416_2114'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('route', models.CharField(max_length=100)),
                ('stops', jsonfield.fields.JSONField()),
                ('type_of_day', models.CharField(max_length=100)),
                ('information', jsonfield.fields.JSONField()),
                ('disabled', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='TripStop',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
            ],
        ),
    ]
