# Generated by Django 3.2.8 on 2024-05-22 21:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_trip_tripstop'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
