# Generated by Django 3.0.14 on 2024-10-09 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_variables_populate_maps_routes'),
    ]

    operations = [
        migrations.AddField(
            model_name='stop',
            name='cleaned_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tripstop',
            name='cleaned_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
