# Generated by Django 3.0.14 on 2024-10-19 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0034_auto_20241019_1907'),
    ]

    operations = [
        migrations.AlterField(
            model_name='info',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='info',
            name='title',
            field=models.TextField(),
        ),
    ]
