# Generated by Django 3.0.14 on 2024-10-19 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0035_auto_20241019_2103'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='info',
            name='message',
        ),
        migrations.RemoveField(
            model_name='info',
            name='title',
        ),
        migrations.AddField(
            model_name='info',
            name='messageDE',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='info',
            name='messageEN',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='info',
            name='messageES',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='info',
            name='messageFR',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='info',
            name='messagePT',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='info',
            name='titleDE',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='info',
            name='titleEN',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='info',
            name='titleES',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='info',
            name='titleFR',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='info',
            name='titlePT',
            field=models.TextField(default=''),
        ),
    ]
