# Generated by Django 5.0.6 on 2026-06-09 20:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialConnection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('apple', 'Apple'), ('google', 'Google')], max_length=20)),
                ('subject', models.CharField(blank=True, max_length=255)),
                ('refresh_token', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_connections', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_social_connection',
                'indexes': [models.Index(fields=['provider', 'subject'], name='user_social_provide_045a18_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='socialconnection',
            constraint=models.UniqueConstraint(fields=('user', 'provider'), name='uniq_social_user_provider'),
        ),
    ]
