# Generated by Django 5.0.6 on 2026-05-21 12:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToolCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Display name.', max_length=100)),
                ('slug', models.SlugField(help_text='URL slug.', max_length=120, unique=True)),
                ('description', models.TextField(blank=True, help_text='SEO description for the category page.')),
                ('icon_class', models.CharField(blank=True, help_text="Font Awesome class, e.g. 'fas fa-shield-alt'.", max_length=60)),
            ],
            options={
                'verbose_name_plural': 'tool categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FreeTool',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Tool display name.', max_length=200)),
                ('slug', models.SlugField(help_text='URL slug, unique per language.', max_length=220)),
                ('tagline', models.CharField(blank=True, help_text='One-line description shown below the title.', max_length=300)),
                ('description', models.TextField(help_text='Detailed description (HTML). Rendered below the tool UI for SEO depth.')),
                ('template_name', models.CharField(help_text="Path to the Django template implementing this tool's UI, e.g. 'free_tools/tools/secret_key_generator.html'.", max_length=200)),
                ('meta_title', models.CharField(blank=True, help_text='Override <title> tag. 50-70 chars. Defaults to name.', max_length=70)),
                ('meta_description', models.CharField(blank=True, help_text='Search engine snippet. 150-160 chars.', max_length=160)),
                ('focus_keyword', models.CharField(blank=True, help_text='Primary keyword to target.', max_length=120)),
                ('canonical_url', models.URLField(blank=True, help_text='Override canonical URL if syndicated.')),
                ('noindex', models.BooleanField(default=False)),
                ('og_image', models.ImageField(blank=True, help_text='1200x630 social sharing image.', null=True, upload_to='free_tools/og/%Y/%m/')),
                ('icon_class', models.CharField(blank=True, help_text='Font Awesome icon class for the tool card.', max_length=60)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], db_index=True, default='draft', max_length=10)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sort_order', models.IntegerField(default=0, help_text='Lower numbers appear first on the index page.')),
                ('language', models.CharField(db_index=True, default='en', max_length=7)),
                ('translation_group', models.UUIDField(blank=True, db_index=True, help_text='UUID linking translations of the same tool.', null=True)),
                ('cta_text', models.CharField(blank=True, max_length=200)),
                ('cta_url', models.URLField(blank=True)),
                ('lead_magnet_title', models.CharField(blank=True, max_length=200)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tools', to='free_tools.toolcategory')),
            ],
            options={
                'ordering': ['sort_order', 'name'],
                'indexes': [models.Index(fields=['status', 'sort_order'], name='free_tools__status_0ffbc9_idx'), models.Index(fields=['language', 'status'], name='free_tools__languag_08391c_idx'), models.Index(fields=['category', 'status'], name='free_tools__categor_32de6b_idx'), models.Index(fields=['translation_group'], name='free_tools__transla_c5c9a9_idx')],
                'unique_together': {('slug', 'language')},
            },
        ),
    ]
