version: "3.1"
   
services:
  django:
    restart: always
    build: ./src
    container_name: saomiguelbus_django_${RUN_ENV:-prod}
    environment:
      - DJANGO_SUPERUSER_USERNAME=${ADMIN_USERNAME:-admin}
      - DJANGO_SUPERUSER_EMAIL=${ADMIN_EMAIL:-admin@admin.com}
      - DJANGO_SUPERUSER_PASSWORD=${ADMIN_PASSWORD:-adminpassword}

  nginx:
    restart: always
    image: nginx:1-alpine
    container_name: saomiguelbus_nginx_${RUN_ENV:-prod}
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d:ro
    ports:
      - 80:80
