# Generated by Django 5.0.6 on 2026-08-08 12:09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenancy", "0017_seed_azores_islands"),
        ("weather", "0003_parishproximity"),
    ]

    operations = [
        migrations.CreateModel(
            name="AtlasCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("legacy_ref", models.JSONField(blank=True, default=dict)),
                ("slug", models.SlugField(max_length=64)),
                ("name", models.JSONField(default=dict)),
                (
                    "group",
                    models.CharField(
                        choices=[
                            ("nature", "Nature"),
                            ("active", "Active"),
                            ("culture", "Culture"),
                            ("wellness", "Wellness"),
                            ("practical", "Practical"),
                            ("food_stay", "Food & stay"),
                            ("transport", "Transport"),
                            ("emergency", "Emergency"),
                        ],
                        default="nature",
                        max_length=32,
                    ),
                ),
                ("icon", models.CharField(default="map-pin", max_length=64)),
                ("color", models.CharField(default="#0B4F9E", max_length=9)),
                ("sort_order", models.PositiveIntegerField(default=100)),
                (
                    "is_safety_critical",
                    models.BooleanField(
                        default=False,
                        help_text="Natural pools, fumaroles, hot springs, volcanic caves — AI-written safety text in this category requires human review before publish.",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("revision", models.BigIntegerField(db_index=True, default=0)),
                (
                    "island",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="tenancy.island"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Atlas categories",
                "ordering": ["sort_order", "slug"],
                "unique_together": {("island", "slug")},
            },
        ),
        migrations.CreateModel(
            name="AtlasRevision",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("current", models.BigIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "island",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="atlas_revision",
                        to="tenancy.island",
                    ),
                ),
            ],
            options={
                "verbose_name": "Atlas revision",
                "verbose_name_plural": "Atlas revisions",
            },
        ),
        migrations.CreateModel(
            name="AtlasTombstone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("legacy_ref", models.JSONField(blank=True, default=dict)),
                (
                    "entity_type",
                    models.CharField(
                        choices=[
                            ("poi", "POI"),
                            ("trail", "Trail"),
                            ("category", "Category"),
                        ],
                        max_length=32,
                    ),
                ),
                ("entity_uid", models.UUIDField()),
                ("source", models.CharField(blank=True, default="", max_length=16)),
                ("revision", models.BigIntegerField(db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "island",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="tenancy.island"
                    ),
                ),
            ],
            options={
                "verbose_name": "Atlas tombstone",
            },
        ),
        migrations.CreateModel(
            name="AtlasTrail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("legacy_ref", models.JSONField(blank=True, default=dict)),
                (
                    "uid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("curated", "Curated"),
                            ("trails", "Trails (first-party)"),
                        ],
                        db_index=True,
                        default="trails",
                        max_length=16,
                    ),
                ),
                (
                    "source_ref",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=200
                    ),
                ),
                ("name", models.JSONField(default=dict)),
                ("description", models.JSONField(blank=True, default=dict)),
                ("difficulty", models.CharField(blank=True, default="", max_length=32)),
                ("distance_km", models.FloatField(blank=True, null=True)),
                ("duration_min", models.PositiveIntegerField(blank=True, null=True)),
                ("ascent_m", models.IntegerField(blank=True, null=True)),
                ("shape", models.CharField(blank=True, default="", max_length=32)),
                ("start_lat", models.FloatField(blank=True, null=True)),
                ("start_lon", models.FloatField(blank=True, null=True)),
                (
                    "parish_slug",
                    models.SlugField(blank=True, default="", max_length=160),
                ),
                ("geojson", models.JSONField(blank=True, default=dict)),
                ("gpx_url", models.CharField(blank=True, default="", max_length=500)),
                ("payload", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(default=True)),
                ("is_published", models.BooleanField(default=False)),
                ("revision", models.BigIntegerField(db_index=True, default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "island",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="tenancy.island"
                    ),
                ),
                (
                    "parish",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="atlas_trails",
                        to="weather.parish",
                    ),
                ),
            ],
            options={
                "verbose_name": "Atlas trail",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="AtlasTrailStage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("legacy_ref", models.JSONField(blank=True, default=dict)),
                ("name", models.JSONField(default=dict)),
                ("sequence", models.PositiveIntegerField(default=1)),
                ("geojson", models.JSONField(blank=True, default=dict)),
                (
                    "island",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="tenancy.island"
                    ),
                ),
                (
                    "trail",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stages",
                        to="atlas.atlastrail",
                    ),
                ),
            ],
            options={
                "verbose_name": "Atlas trail stage",
                "ordering": ["sequence"],
            },
        ),
        migrations.CreateModel(
            name="AtlasPoi",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("legacy_ref", models.JSONField(blank=True, default=dict)),
                (
                    "uid",
                    models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("poi", "POI"),
                            ("viewpoint", "Viewpoint"),
                            ("trailhead", "Trailhead"),
                            ("beach", "Beach"),
                        ],
                        default="poi",
                        max_length=32,
                    ),
                ),
                (
                    "tier",
                    models.CharField(
                        choices=[
                            ("curated", "Curated"),
                            ("enriched", "Enriched"),
                            ("standard", "Standard"),
                        ],
                        db_index=True,
                        default="standard",
                        max_length=16,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("curated", "Curated"),
                            ("osm", "OpenStreetMap"),
                            ("transit", "Transit (first-party)"),
                            ("minibus", "Mini Bus (first-party)"),
                            ("trails", "Trails (first-party)"),
                        ],
                        db_index=True,
                        default="osm",
                        max_length=16,
                    ),
                ),
                (
                    "source_ref",
                    models.CharField(
                        blank=True, db_index=True, default="", max_length=200
                    ),
                ),
                ("name", models.JSONField(default=dict)),
                ("description", models.JSONField(blank=True, default=dict)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("elevation_m", models.IntegerField(blank=True, null=True)),
                (
                    "parish_slug",
                    models.SlugField(blank=True, default="", max_length=160),
                ),
                ("media", models.JSONField(blank=True, default=list)),
                ("opening_hours", models.JSONField(blank=True, default=dict)),
                ("tips", models.JSONField(blank=True, default=dict)),
                ("accessibility", models.JSONField(blank=True, default=dict)),
                ("external_refs", models.JSONField(blank=True, default=dict)),
                ("enriched_at", models.DateTimeField(blank=True, null=True)),
                (
                    "enrichment_model",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("is_safety_critical", models.BooleanField(default=False)),
                ("is_safety_reviewed", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("is_published", models.BooleanField(default=False)),
                ("revision", models.BigIntegerField(db_index=True, default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pois",
                        to="atlas.atlascategory",
                    ),
                ),
                (
                    "island",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="tenancy.island"
                    ),
                ),
                (
                    "parish",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="atlas_pois",
                        to="weather.parish",
                    ),
                ),
            ],
            options={
                "verbose_name": "Atlas POI",
                "ordering": ["id"],
                "indexes": [
                    models.Index(
                        fields=["island", "revision"],
                        name="atlas_atlas_island__6924ae_idx",
                    ),
                    models.Index(
                        fields=["island", "is_published", "is_active"],
                        name="atlas_atlas_island__0beef1_idx",
                    ),
                    models.Index(
                        fields=["island", "latitude", "longitude"],
                        name="atlas_atlas_island__ed0f4b_idx",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="atlaspoi",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("tier", "curated"),
                    models.Q(("source", "curated"), _negated=True),
                    _negated=True,
                ),
                name="atlas_curated_tier_requires_curated_source",
            ),
        ),
        migrations.AddConstraint(
            model_name="atlaspoi",
            constraint=models.CheckConstraint(
                check=models.Q(
                    ("is_published", True),
                    ("is_safety_critical", True),
                    ("is_safety_reviewed", False),
                    _negated=True,
                ),
                name="atlas_safety_critical_requires_review_before_publish",
            ),
        ),
        migrations.AddIndex(
            model_name="atlastombstone",
            index=models.Index(
                fields=["island", "revision"], name="atlas_atlas_island__587ab6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="atlastrail",
            index=models.Index(
                fields=["island", "revision"], name="atlas_atlas_island__d98793_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="atlastrail",
            index=models.Index(
                fields=["island", "is_published", "is_active"],
                name="atlas_atlas_island__8149d2_idx",
            ),
        ),
    ]
