# Generated by Django 4.2.29 on 2026-06-02 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenancy", "0005_enable_news_feature_flag"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsSource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("legacy_ref", models.JSONField(blank=True, default=dict)),
                ("name", models.CharField(max_length=120)),
                ("rss_url", models.URLField(max_length=500)),
                ("language", models.CharField(default="pt", max_length=8)),
                ("active", models.BooleanField(default=True)),
                (
                    "island",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="tenancy.island"
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "unique_together": {("island", "rss_url")},
            },
        ),
        migrations.CreateModel(
            name="NewsArticle",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("legacy_ref", models.JSONField(blank=True, default=dict)),
                ("title", models.CharField(max_length=500)),
                ("summary", models.TextField(blank=True, default="")),
                ("link", models.URLField(max_length=1000)),
                ("published_at", models.DateTimeField(db_index=True)),
                ("category", models.CharField(blank=True, default="", max_length=64)),
                ("content_hash", models.CharField(db_index=True, max_length=64)),
                (
                    "island",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="tenancy.island"
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="articles",
                        to="news.newssource",
                    ),
                ),
            ],
            options={
                "ordering": ["-published_at"],
                "indexes": [
                    models.Index(
                        fields=["island", "-published_at"],
                        name="news_newsar_island__239080_idx",
                    ),
                    models.Index(
                        fields=["island", "category"],
                        name="news_newsar_island__e4cf61_idx",
                    ),
                ],
                "unique_together": {("island", "link")},
            },
        ),
    ]
