# Generated by Django 4.2.29 on 2026-06-19 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenancy", "0013_enable_minibus_feature_flag"),
    ]

    operations = [
        migrations.CreateModel(
            name="MinibusLine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("legacy_ref", models.JSONField(blank=True, default=dict)),
                ("code", models.CharField(max_length=4)),
                ("slug", models.SlugField(max_length=32)),
                ("name_pt", models.CharField(max_length=120)),
                ("name_en", models.CharField(max_length=120)),
                ("color", models.CharField(max_length=7)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                ("service_summary", models.JSONField(blank=True, default=dict)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "island",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="tenancy.island"
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "code"],
            },
        ),
        migrations.CreateModel(
            name="MinibusImportMeta",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("legacy_ref", models.JSONField(blank=True, default=dict)),
                ("source_url", models.URLField(max_length=255)),
                (
                    "source_revision",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("imported_at", models.DateTimeField(blank=True, null=True)),
                ("tariffs_effective_date", models.DateField(blank=True, null=True)),
                (
                    "island",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="tenancy.island"
                    ),
                ),
            ],
            options={
                "verbose_name": "Mini Bus import metadata",
                "verbose_name_plural": "Mini Bus import metadata",
            },
        ),
        migrations.CreateModel(
            name="MinibusDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("legacy_ref", models.JSONField(blank=True, default=dict)),
                ("slug", models.SlugField(max_length=64)),
                ("title_pt", models.CharField(max_length=160)),
                ("title_en", models.CharField(max_length=160)),
                (
                    "doc_type",
                    models.CharField(
                        choices=[
                            ("timetable", "Timetable"),
                            ("network_map", "Network map"),
                            ("tariffs", "Tariffs"),
                            ("schematic", "Schematic"),
                        ],
                        max_length=32,
                    ),
                ),
                ("source_filename", models.CharField(max_length=255)),
                ("file", models.FileField(blank=True, upload_to="minibus/")),
                ("is_active", models.BooleanField(default=True)),
                (
                    "island",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="tenancy.island"
                    ),
                ),
                (
                    "line",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="documents",
                        to="minibus.minibusline",
                    ),
                ),
            ],
            options={
                "ordering": ["doc_type", "slug"],
            },
        ),
        migrations.CreateModel(
            name="MinibusTariff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("legacy_ref", models.JSONField(blank=True, default=dict)),
                ("key", models.SlugField(max_length=64)),
                ("label_pt", models.CharField(max_length=160)),
                ("label_en", models.CharField(max_length=160)),
                ("price_eur", models.DecimalField(decimal_places=2, max_digits=6)),
                ("sort_order", models.PositiveSmallIntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "island",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="tenancy.island"
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "key"],
                "unique_together": {("island", "key")},
            },
        ),
        migrations.AddIndex(
            model_name="minibusline",
            index=models.Index(
                fields=["island", "is_active"], name="minibus_min_island__cca1d9_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="minibusline",
            unique_together={("island", "code"), ("island", "slug")},
        ),
        migrations.AlterUniqueTogether(
            name="minibusdocument",
            unique_together={("island", "slug")},
        ),
    ]
