# Generated by Django 3.0.14 on 2025-06-16 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='verification_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
