# Generated by Django 3.0.14 on 2022-07-15 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stop',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
