# Generated by Django 3.0.14 on 2022-07-15 14:07

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20220715_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='information',
            field=jsonfield.fields.JSONField(),
        ),
        migrations.RemoveField(
            model_name='route',
            name='stops',
        ),
        migrations.AddField(
            model_name='route',
            name='stops',
            field=jsonfield.fields.JSONField(default=None),
            preserve_default=False,
        ),
    ]
