# Generated by Django 3.0.14 on 2023-07-13 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20230713_1018'),
    ]

    operations = [
        migrations.AddField(
            model_name='ad',
            name='seen',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='ad',
            name='platform',
            field=models.CharField(choices=[('android', 'Android'), ('ios', 'iOS'), ('web', 'Web')], max_length=100),
        ),
    ]
