# Generated by Django 3.0.14 on 2023-07-13 11:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20230713_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='end',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='ad',
            name='start',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
