# Generated by Django 3.0.14 on 2023-07-13 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_auto_20230713_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='action',
            field=models.CharField(blank=True, choices=[('open', 'Open URL'), ('directions', 'Get Directions To'), ('call', 'Call To Number'), ('sms', 'Send SMS'), ('email', 'Send Email')], max_length=100, null=True),
        ),
    ]
