# Generated by Django 3.0.14 on 2024-04-16 20:18

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0023_holiday'),
    ]

    operations = [
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data', jsonfield.fields.JSONField()),
            ],
        ),
    ]
