# Generated by Django 3.0.14 on 2024-10-08 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0027_trip_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='variables',
            name='populate_maps_routes',
            field=models.BooleanField(default=False),
        ),
    ]
