# Generated by Django 3.0.14 on 2024-10-09 14:45

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_auto_20241009_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='cleaned_stops',
            field=jsonfield.fields.JSONField(blank=True, null=True),
        ),
    ]
