# Generated by Django 3.0.14 on 2024-10-17 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0032_auto_20241013_2154'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIFeedback',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('language', models.CharField(max_length=10, null=True)),
                ('first_time', models.BooleanField(null=True)),
                ('residence_status', models.CharField(max_length=50, null=True)),
                ('guide_preference', models.CharField(max_length=50, null=True)),
                ('payment_willingness', models.CharField(max_length=50, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
