# Generated by Django 3.0.14 on 2024-10-26 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_auto_20241019_2106'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailOpen',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email_template_id', models.IntegerField()),
                ('contact_id', models.IntegerField()),
                ('clicks', models.IntegerField(default=0)),
            ],
        ),
    ]
