# Generated by Django 4.2.29 on 2026-06-03 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenancy", "0011_enable_weather_feature_flag"),
    ]

    operations = [
        migrations.CreateModel(
            name="Parish",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("legacy_ref", models.JSONField(blank=True, default=dict)),
                ("name", models.CharField(max_length=120)),
                ("slug", models.SlugField(max_length=160)),
                ("concelho", models.CharField(max_length=80)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("is_active", models.BooleanField(default=True)),
                (
                    "island",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="tenancy.island"
                    ),
                ),
            ],
            options={
                "ordering": ["concelho", "name"],
                "indexes": [
                    models.Index(
                        fields=["island", "concelho"],
                        name="weather_par_island__12382e_idx",
                    ),
                    models.Index(
                        fields=["island", "is_active"],
                        name="weather_par_island__71df7d_idx",
                    ),
                ],
                "unique_together": {("island", "slug")},
            },
        ),
    ]
