# Generated by Django 4.2.29 on 2026-06-25 12:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("tenancy", "0015_appreleaseconfig_in_app_review_enabled"),
        ("weather", "0002_seed_parishes_and_beat"),
    ]

    operations = [
        migrations.CreateModel(
            name="ParishProximity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("legacy_ref", models.JSONField(blank=True, default=dict)),
                ("source_module", models.CharField(db_index=True, max_length=64)),
                ("source_ref", models.CharField(db_index=True, max_length=128)),
                ("distance_km", models.FloatField()),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                (
                    "island",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="tenancy.island"
                    ),
                ),
                (
                    "parish",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="proximity_mappings",
                        to="weather.parish",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["island", "source_module", "source_ref"],
                        name="weather_par_island__a0cb9d_idx",
                    )
                ],
                "unique_together": {("island", "source_module", "source_ref")},
            },
        ),
    ]
