# Generated by Django 5.0.6 on 2026-06-01 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LegacyAIFeedback',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('language', models.CharField(blank=True, max_length=10, null=True)),
                ('first_time', models.BooleanField(blank=True, null=True)),
                ('residence_status', models.CharField(blank=True, max_length=50, null=True)),
                ('guide_preference', models.CharField(blank=True, max_length=50, null=True)),
                ('payment_willingness', models.CharField(blank=True, max_length=50, null=True)),
                ('timestamp', models.DateTimeField()),
            ],
            options={
                'db_table': 'app_aifeedback',
            },
        ),
        migrations.CreateModel(
            name='LegacyData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('data', models.JSONField()),
                ('origin', models.CharField(blank=True, max_length=100, null=True)),
                ('destination', models.CharField(blank=True, max_length=100, null=True)),
                ('language_code', models.CharField(blank=True, max_length=100, null=True)),
                ('time', models.CharField(blank=True, max_length=100, null=True)),
                ('platform', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'app_data',
            },
        ),
        migrations.CreateModel(
            name='LegacyEmailOpen',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email_template_id', models.IntegerField()),
                ('contact_id', models.IntegerField()),
                ('clicks', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'app_emailopen',
            },
        ),
        migrations.CreateModel(
            name='LegacyTrip',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('route', models.CharField(max_length=100)),
                ('stops', models.JSONField()),
                ('cleaned_stops', models.JSONField()),
                ('type_of_day', models.CharField(max_length=100)),
                ('information', models.JSONField()),
                ('disabled', models.BooleanField(default=False)),
                ('added', models.DateTimeField()),
                ('likes', models.IntegerField(default=0)),
                ('dislikes', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'app_trip',
            },
        ),
        migrations.CreateModel(
            name='LegacyTripStop',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('cleaned_name', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'app_tripstop',
            },
        ),
    ]
