# Generated by Django 5.0.6 on 2026-06-04 17:15

import billing.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("billing", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Entitlement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(blank=True, db_index=True, max_length=254)),
                (
                    "tier",
                    models.CharField(
                        choices=[("free", "Free"), ("premium", "Premium")],
                        default="premium",
                        max_length=16,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("legacy_email", "Legacy email allow-list"),
                            ("manual", "Manual grant"),
                            ("revenuecat", "RevenueCat (IAP)"),
                            ("stripe", "Stripe"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("canceled", "Canceled"),
                            ("expired", "Expired"),
                        ],
                        default="active",
                        max_length=16,
                    ),
                ),
                (
                    "platform",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("ios", "iOS"),
                            ("android", "Android"),
                            ("web", "Web"),
                        ],
                        max_length=10,
                    ),
                ),
                ("external_id", models.CharField(blank=True, max_length=255)),
                ("current_period_end", models.DateTimeField(blank=True, null=True)),
                ("features", models.JSONField(default=billing.models.default_features)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entitlements",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "billing_entitlement",
                "indexes": [
                    models.Index(
                        fields=["user", "status"], name="billing_ent_user_id_a06777_idx"
                    ),
                    models.Index(
                        fields=["email", "status"], name="billing_ent_email_29a145_idx"
                    ),
                    models.Index(
                        fields=["source", "status"],
                        name="billing_ent_source_1376df_idx",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="entitlement",
            constraint=models.UniqueConstraint(
                condition=models.Q(("user__isnull", False)),
                fields=("user", "source"),
                name="uniq_entitlement_user_source",
            ),
        ),
    ]
