# Generated by Django 5.0.6 on 2026-08-14 14:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0018_seed_sao_miguel_island'),
        ('transit', '0005_dataset_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_ref', models.JSONField(blank=True, default=dict)),
                ('kind', models.CharField(choices=[('schedules', 'Schedules'), ('tariffs', 'Tariffs')], db_index=True, default='schedules', max_length=16)),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('partial', 'Partial')], db_index=True, default='running', max_length=16)),
                ('started_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('request_count', models.PositiveIntegerField(default=0)),
                ('sampled_dates', models.JSONField(default=list)),
                ('stats', models.JSONField(default=dict)),
                ('error', models.TextField(blank=True, default='')),
                ('island', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.island')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceObservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_ref', models.JSONField(blank=True, default=dict)),
                ('dataset', models.CharField(choices=[('legacy', 'Legacy network'), ('azoresbus', 'AzoresBus 2026')], db_index=True, default='azoresbus', max_length=16)),
                ('external_id', models.CharField(db_index=True, max_length=32)),
                ('date', models.DateField(db_index=True)),
                ('island', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.island')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='observations', to='azoresbus.syncrun')),
            ],
        ),
        migrations.CreateModel(
            name='TariffSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_ref', models.JSONField(blank=True, default=dict)),
                ('source_url', models.URLField(max_length=255)),
                ('effective_date', models.DateField(blank=True, null=True)),
                ('upstream_etag', models.CharField(blank=True, default='', max_length=128)),
                ('upstream_modified_at', models.DateTimeField(blank=True, null=True)),
                ('fetched_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('payload', models.JSONField(default=dict)),
                ('content_hash', models.CharField(db_index=True, max_length=64)),
                ('is_current', models.BooleanField(default=True)),
                ('island', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.island')),
            ],
            options={
                'ordering': ['-effective_date', '-fetched_at'],
            },
        ),
        migrations.CreateModel(
            name='ExternalJourney',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_ref', models.JSONField(blank=True, default=dict)),
                ('dataset', models.CharField(choices=[('legacy', 'Legacy network'), ('azoresbus', 'AzoresBus 2026')], db_index=True, default='azoresbus', max_length=16)),
                ('external_id', models.CharField(db_index=True, max_length=32)),
                ('route_ext_id', models.CharField(db_index=True, max_length=32)),
                ('direction', models.PositiveSmallIntegerField(default=0)),
                ('shape', models.TextField(blank=True, default='')),
                ('payload_hash', models.CharField(blank=True, default='', max_length=64)),
                ('identity', models.CharField(blank=True, default='', max_length=128)),
                ('island', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.island')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_journeys', to='transit.trip')),
            ],
            options={
                'ordering': ['external_id'],
                'unique_together': {('island', 'dataset', 'external_id')},
            },
        ),
        migrations.CreateModel(
            name='ExternalStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_ref', models.JSONField(blank=True, default=dict)),
                ('dataset', models.CharField(choices=[('legacy', 'Legacy network'), ('azoresbus', 'AzoresBus 2026')], db_index=True, default='azoresbus', max_length=16)),
                ('external_id', models.CharField(db_index=True, max_length=32)),
                ('code', models.CharField(db_index=True, max_length=32)),
                ('name', models.CharField(max_length=200)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('island', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.island')),
                ('stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='external_stops', to='transit.stop')),
            ],
            options={
                'ordering': ['code'],
                'unique_together': {('island', 'dataset', 'external_id')},
            },
        ),
        migrations.AddIndex(
            model_name='syncrun',
            index=models.Index(fields=['island', 'kind', 'status', '-started_at'], name='azoresbus_s_island__1cd483_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceobservation',
            index=models.Index(fields=['island', 'dataset', 'date'], name='azoresbus_s_island__bf7204_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='serviceobservation',
            unique_together={('island', 'dataset', 'external_id', 'date')},
        ),
        migrations.AddIndex(
            model_name='tariffsnapshot',
            index=models.Index(fields=['island', 'is_current'], name='azoresbus_t_island__334181_idx'),
        ),
    ]
