# Generated by Django 5.0.6 on 2026-09-03 10:45

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("azoresbus", "0002_periodic_tasks"),
        ("tenancy", "0020_enable_trails_all_islands"),
    ]

    operations = [
        migrations.CreateModel(
            name="LiveActivityRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("legacy_ref", models.JSONField(blank=True, default=dict)),
                (
                    "push_token",
                    models.CharField(db_index=True, max_length=200, unique=True),
                ),
                (
                    "environment",
                    models.CharField(
                        choices=[
                            ("development", "Development"),
                            ("production", "Production"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "activity_key",
                    models.CharField(blank=True, default="", max_length=64),
                ),
                ("legs", models.JSONField(default=list)),
                ("expires_at", models.DateTimeField()),
                ("ended_at", models.DateTimeField(blank=True, null=True)),
                ("last_pushed_at", models.DateTimeField(blank=True, null=True)),
                ("failure_count", models.PositiveSmallIntegerField(default=0)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "island",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="tenancy.island"
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["island", "ended_at", "expires_at"],
                        name="azoresbus_l_island__3def44_idx",
                    )
                ],
            },
        ),
    ]
