# Generated by Django 5.0.6 on 2026-05-21 12:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Display name.', max_length=80)),
                ('slug', models.SlugField(help_text='URL slug.', max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Display name.', max_length=100)),
                ('slug', models.SlugField(help_text='URL slug.', max_length=120, unique=True)),
                ('description', models.TextField(blank=True, help_text='SEO description for the category archive page (1-2 sentences).')),
                ('parent', models.ForeignKey(blank=True, help_text='Parent category for hierarchical organization.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='blog.category')),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Display title shown to readers.', max_length=250)),
                ('slug', models.SlugField(help_text='URL-safe identifier. Should be unique per language.', max_length=280)),
                ('body', models.TextField(help_text='Full post content (HTML).')),
                ('excerpt', models.TextField(blank=True, help_text='Short summary for blog index cards and RSS. Falls back to first 160 chars of body if empty.', max_length=500)),
                ('meta_title', models.CharField(blank=True, help_text='Override for <title> tag. 50-70 chars. Defaults to title.', max_length=70)),
                ('meta_description', models.CharField(blank=True, help_text='Search engine snippet. 150-160 chars.', max_length=160)),
                ('focus_keyword', models.CharField(blank=True, help_text='Primary keyword to target (internal SEO scoring).', max_length=120)),
                ('canonical_url', models.URLField(blank=True, help_text='Override canonical URL for syndicated content.')),
                ('noindex', models.BooleanField(default=False, help_text='Add noindex meta tag to exclude from search engines.')),
                ('featured_image', models.ImageField(blank=True, help_text='Hero image displayed at the top of the post.', null=True, upload_to='blog/featured/%Y/%m/')),
                ('featured_image_alt', models.CharField(blank=True, help_text='Descriptive alt text for the featured image.', max_length=125)),
                ('og_image', models.ImageField(blank=True, help_text='1200x630 image for social sharing. Falls back to featured_image.', null=True, upload_to='blog/og/%Y/%m/')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('scheduled', 'Scheduled')], db_index=True, default='draft', max_length=10)),
                ('published_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('word_count', models.PositiveIntegerField(default=0, editable=False)),
                ('language', models.CharField(db_index=True, default='en', help_text='ISO 639-1 code (en, fr, es, pt-BR).', max_length=7)),
                ('translation_group', models.UUIDField(blank=True, db_index=True, help_text='Shared UUID linking all translations of the same post.', null=True)),
                ('cta_text', models.CharField(blank=True, help_text="Primary CTA button text, e.g. 'Get the Free Checklist'.", max_length=200)),
                ('cta_url', models.URLField(blank=True, help_text='Where the CTA button links to.')),
                ('lead_magnet_title', models.CharField(blank=True, help_text='Name of the lead magnet offered in this post.', max_length=200)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='blog_posts', to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(blank=True, help_text='One primary category per post.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='blog.category')),
                ('tags', models.ManyToManyField(blank=True, help_text='Cross-cutting topic tags. Use 3-5 per post.', related_name='posts', to='blog.tag')),
            ],
            options={
                'ordering': ['-published_at'],
                'indexes': [models.Index(fields=['status', 'published_at'], name='blog_blogpo_status_aa5436_idx'), models.Index(fields=['language', 'status'], name='blog_blogpo_languag_629ba6_idx'), models.Index(fields=['category', 'status'], name='blog_blogpo_categor_2e8dab_idx'), models.Index(fields=['translation_group'], name='blog_blogpo_transla_17eba6_idx')],
                'unique_together': {('slug', 'language')},
            },
        ),
    ]
