"""
Django settings for src project.

Generated by 'django-admin startproject' using Django 3.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

PROJECT_NAME = "SaoMiguelBus" # This will change the project name across several parts of the project
PROJECT_URL = "https://saomiguelbus.com" # This will change the project URL across several parts of the project

### CHANGE THE CODE BELOW TO MANAGE WHICH APPS TO USE ###
## djast is intended to be used with all the apps below, but you can personalize it at your own risk ##
apps = [
    ('allauth.socialaccount.providers.google', False),
    ('allauth.socialaccount.providers.github', False),
    ('admin_interface', True),
    ('rest_framework', True),
    ('axes', True),
    ('landing_page', False),
    ('documentation', False),
    ('app', False),
    ('legal', True),
    ('stripe_payments', False),
    ('blog', False),
    ('free_tools', False),
    ('tailwind', False),
    ('django_browser_reload', False),
    ('tenancy', True),
    ('transit', True),
    ('analytics', True),
    ('consent', True),
    ('billing', True),
    ('compat', True),
    ('legacy_archive', True),
    ('news', True),
    ('seismic', True),
    ('trails', True),
    ('marketplace', True),
    ('traffic', True),
]

import os
from pathlib import Path
from decouple import config

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

SECRET_KEY = config('SECRET_KEY', default='YOUR_SECRET_KEY')

DEBUG = config('DEBUG', default=True, cast=bool)

# Service ports (override in src/src/.env or repo-root .env for Docker Compose)
WEB_HOST = config('WEB_HOST', default='127.0.0.1')
WEB_PORT = config('WEB_PORT', default='8000')
WEB_CONTAINER_PORT = config('WEB_CONTAINER_PORT', default=WEB_PORT)
DB_HOST = config('DB_HOST', default='')
DB_PORT = config('DB_PORT', default='5432')
DB_NAME = config('DB_NAME', default='postgres')
DB_USER = config('DB_USER', default='')
DB_PASSWORD = config('DB_PASSWORD', default='')
REDIS_HOST = config('REDIS_HOST', default='localhost')
REDIS_PORT = config('REDIS_PORT', default='6379')

DEFAULT_ISLAND_KEY = config('DEFAULT_ISLAND_KEY', default='sao-miguel')
ALLOW_INACTIVE_ISLANDS = config('ALLOW_INACTIVE_ISLANDS', default=DEBUG, cast=bool)

AUTH_KEY = config('AUTH_KEY', default='SMBFj56xBCLc986j6odk3AK6fJa95k')
GOOGLE_MAPS_API_KEY = config('GOOGLE_MAPS_API_KEY', default='dummy_key')

# Public transit API — allow webapp/PWA cross-origin requests
CORS_ALLOW_ALL_ORIGINS = config('CORS_ALLOW_ALL_ORIGINS', default=True, cast=bool)

REST_FRAMEWORK = {
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ],
    'DEFAULT_THROTTLE_RATES': {
        'directions': '30/min',
        'marketplace_write': '20/min',
        'traffic_write': '30/min',
    },
}


def _csv_env(name: str, *, default: str) -> list[str]:
    """Parse a comma-separated environment variable into a list of strings."""
    return [part.strip() for part in config(name, default=default).split(',') if part.strip()]


ALLOWED_HOSTS = _csv_env(
    'ALLOWED_HOSTS',
    default='127.0.0.1,localhost,0.0.0.0,.vercel.app',
)

_cors_default = (
    f'http://127.0.0.1:{WEB_PORT},http://localhost:{WEB_PORT}'
    if DEBUG
    else ''
)
CORS_ALLOWED_ORIGINS = _csv_env('CORS_ALLOWED_ORIGINS', default=_cors_default)
CSRF_TRUSTED_ORIGINS = _csv_env(
    'CSRF_TRUSTED_ORIGINS',
    default=','.join(CORS_ALLOWED_ORIGINS),
)

MEDIA_ROOT = os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

SITE_ID = 1

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sitemaps',
    'corsheaders',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'tenancy.middleware.TenantMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]
            
INTERNAL_IPS = [
    "127.0.0.1",
]


ROOT_URLCONF = 'src.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'debug': DEBUG,
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'context_processors.project_name',
                'context_processors.analytics_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'src.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

# Database — Postgres when DB_HOST is set (Docker Compose / production), else SQLite in DEBUG.
# Without this, celery-worker/beat each get their own empty db.sqlite3 when DEBUG=True.
if DB_HOST:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': DB_NAME,
            'USER': DB_USER,
            'PASSWORD': DB_PASSWORD,
            'HOST': DB_HOST,
            'PORT': DB_PORT,
        }
    }
elif DEBUG:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': DB_NAME,
            'USER': DB_USER,
            'PASSWORD': DB_PASSWORD,
            'HOST': DB_HOST,
            'PORT': DB_PORT,
        }
    }


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'index'
LOGOUT_REDIRECT_URL = 'login'

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, 'static')

STORAGES = {
    'default': {
        'BACKEND': 'django.core.files.storage.FileSystemStorage',
    },
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedStaticFilesStorage',
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


### These settings are used to enable or disable certain features in the project dynamically based on 'apps' variable ###
## You don't need to change anything here (unless you want to), just add or remove apps from the 'apps' variable above ##
# CHANGE THE CODE BELOW AT YOUR OWN RISK #
def define_django_allauth_settings(social_providers = []):
    ''' Django Allauth Settings '''
    global AUTHENTICATION_BACKENDS, SOCIALACCOUNT_PROVIDERS, ACCOUNT_AUTHENTICATION_METHOD, ACCOUNT_EMAIL_REQUIRED, ACCOUNT_USERNAME_REQUIRED, ACCOUNT_EMAIL_VERIFICATION, EMAIL_BACKEND, RESEND_API_KEY, DEFAULT_FROM_EMAIL, EMAIL_HOST, EMAIL_PORT, EMAIL_USE_TLS, EMAIL_HOST_USER, EMAIL_HOST_PASSWORD
    
    if len(social_providers) > 0:
        SOCIALACCOUNT_PROVIDERS = {}
        for social_provider in social_providers:
            if social_provider == 'google':
                SOCIALACCOUNT_PROVIDERS['google'] = {
                    'APP': {
                        'client_id': config('GOOGLE_CLIENT_ID', default=''),
                        'secret': config('GOOGLE_SECRET', default=''),
                        'key': ''
                    },
                    'SCOPE': [
                        'profile',
                        'email',
                    ],
                    'AUTH_PARAMS': {
                        'access_type': 'offline',
                    },
                    'OAUTH_PKCE_ENABLED': True,
                }
            elif social_provider == 'github':
                SOCIALACCOUNT_PROVIDERS['github'] = {
                    'APP': {
                        'client_id': config('GITHUB_CLIENT_ID', default=''),
                        'secret': config('GITHUB_SECRET', default=''),
                        'key': ''
                    },
                    'SCOPE': [
                        'user:email', 
                    ],
                }
    else:
        AUTHENTICATION_BACKENDS = []
        if ('axes', True) in apps:
            AUTHENTICATION_BACKENDS = [
                'axes.backends.AxesStandaloneBackend',
            ]
            
        AUTHENTICATION_BACKENDS += [
            'django.contrib.auth.backends.ModelBackend',
        ]
        
        if 'allauth' in INSTALLED_APPS:
            AUTHENTICATION_BACKENDS += [
                'allauth.account.auth_backends.AuthenticationBackend'
            ]
        
        # Make both username and email required
        ACCOUNT_USERNAME_REQUIRED = config('ACCOUNT_USERNAME_REQUIRED', default=True, cast=bool)
        ACCOUNT_EMAIL_REQUIRED = config('ACCOUNT_EMAIL_REQUIRED', default=True, cast=bool)

        # Allow login via either username or email
        ACCOUNT_AUTHENTICATION_METHOD = config('ACCOUNT_AUTHENTICATION_METHOD', default='username_email')

        # Send a verification email, but don't require it for login
        ACCOUNT_EMAIL_VERIFICATION = config('ACCOUNT_EMAIL_VERIFICATION', default='mandatory')


        if DEBUG:
            EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
        else:
            if config('USE_SMTP', default=False, cast=bool):
                EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
                EMAIL_HOST = config('EMAIL_HOST', default='')
                EMAIL_PORT = config('EMAIL_PORT', default='')
                EMAIL_USE_TLS = config('EMAIL_USE_TLS', default=False, cast=bool)
                EMAIL_HOST_USER = config('EMAIL_HOST_USER', default='')
                EMAIL_HOST_PASSWORD = config('EMAIL_HOST_PASSWORD', default='')
            else:
                EMAIL_BACKEND = 'shared.resend_backend.ResendEmailBackend'
                RESEND_API_KEY = config('RESEND_API_KEY', default='')
        DEFAULT_FROM_EMAIL = config('DEFAULT_FROM_EMAIL', default='')

def define_django_axes_settings():
    ''' Django Axes Settings '''
    global AXES_FAILURE_LIMIT, AXES_COOLOFF_TIME, AXES_RESET_ON_SUCCESS
    
    AXES_FAILURE_LIMIT = config('AXES_FAILURE_LIMIT', default=10, cast=int)    
    AXES_COOLOFF_TIME = config('AXES_COOLOFF_TIME', default=1, cast=int)
    AXES_RESET_ON_SUCCESS = config('AXES_RESET_ON_SUCCESS', default=True, cast=bool)

def define_stripe_payments_settings():
    ''' Stripe Payments Settings '''
    global STRIPE_PUBLIC_KEY, STRIPE_SECRET_KEY, STRIPE_WEBHOOK_SECRET, PRODUCT_PRICE_ID, COUPON_ID, PAYMENT_METHODS, REDIRECT_DOMAIN
    prefix = 'TEST_' if DEBUG else ''
    STRIPE_PUBLIC_KEY = config(f'{prefix}STRIPE_PUBLIC_KEY', default='')
    STRIPE_SECRET_KEY = config(f'{prefix}STRIPE_SECRET_KEY', default='')
    STRIPE_WEBHOOK_SECRET = config(f'{prefix}STRIPE_WEBHOOK_SECRET', default='')
    PRODUCT_PRICE_ID = config(f'{prefix}PRODUCT_PRICE_ID', default='')
    COUPON_ID = config(f'{prefix}COUPON_ID', default='')
    _redirect_default = f'http://{WEB_HOST}:{WEB_PORT}/payment'
    REDIRECT_DOMAIN = config(f'{prefix}REDIRECT_DOMAIN', default=_redirect_default)
    PAYMENT_METHODS = config('PAYMENT_METHODS', default='card,paypal,link').split(',')

AUTHENTICATION_REQUIRED = config('AUTHENTICATION_REQUIRED', default=False, cast=bool)      
if AUTHENTICATION_REQUIRED:
    INSTALLED_APPS.append('django.contrib.sites')
    INSTALLED_APPS.append('user_management.apps.UserManagementConfig')
    INSTALLED_APPS.append('allauth')
    INSTALLED_APPS.append('allauth.account')
    define_django_allauth_settings()
    
GOOGLE_ANALYTICS_ID = config('GOOGLE_ANALYTICS_ID', default=None)
CONSENT_REQUIRED = config('CONSENT_REQUIRED', default=False, cast=bool)
GA_DEBUG_MODE = config('GA_DEBUG_MODE', default=DEBUG, cast=bool)

social_providers = []
for app, should_add in apps:
    if should_add and app not in INSTALLED_APPS:
        if 'allauth.socialaccount.' in app and 'allauth.socialaccount' not in INSTALLED_APPS:
            if not AUTHENTICATION_REQUIRED:
                raise Exception('Social accounts require authentication to be enabled. Enable AUTHENTICATION_REQUIRED in your .env file.')
            INSTALLED_APPS.append('allauth.socialaccount')
        INSTALLED_APPS.append(app)
        if 'allauth.socialaccount.providers.' in app:
            social_providers.append(app.replace('allauth.socialaccount.providers.', ''))
        if app == 'tailwind':
            INSTALLED_APPS.append('theme')
            TAILWIND_APP_NAME = 'theme'
        elif app == 'admin_interface':
            INSTALLED_APPS.append('colorfield')
            INSTALLED_APPS = ['admin_interface', 'colorfield'] + [i for i in INSTALLED_APPS if i not in ['admin_interface', 'colorfield']]
            X_FRAME_OPTIONS = "SAMEORIGIN"
            SILENCED_SYSTEM_CHECKS = ["security.W019"]
        elif app == 'axes':
            define_django_axes_settings()
        elif app == 'stripe_payments':
            define_stripe_payments_settings()
INSTALLED_APPS.append('shared')
            
if 'landing_page' in INSTALLED_APPS and 'app' not in INSTALLED_APPS:
    raise Exception('The \'landing_page\' requires the \'app\' to be enabled. Please enable it.')
if len(social_providers) > 0:
    define_django_allauth_settings(social_providers)
            
if 'user_management.apps.UserManagementConfig' in INSTALLED_APPS:
    MIDDLEWARE.append('user_management.middleware.LoginRequiredMiddleware')
if 'django_browser_reload' in INSTALLED_APPS:
    MIDDLEWARE.append('django_browser_reload.middleware.BrowserReloadMiddleware')
if 'allauth' in INSTALLED_APPS:
    MIDDLEWARE.append('allauth.account.middleware.AccountMiddleware')
if 'axes' in INSTALLED_APPS:
    MIDDLEWARE.append('axes.middleware.AxesMiddleware')
    
### Celery Configuration ###
_default_redis = f'redis://{REDIS_HOST}:{REDIS_PORT}'
CELERY_BROKER_URL = config('CELERY_BROKER_URL', default=f'{_default_redis}/0')
CELERY_RESULT_BACKEND = config('CELERY_RESULT_BACKEND', default=f'{_default_redis}/0')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = TIME_ZONE
CELERY_TASK_TRACK_STARTED = True
CELERY_TASK_TIME_LIMIT = 30 * 60  # 30 minutes hard limit
CELERY_TASK_SOFT_TIME_LIMIT = 25 * 60  # 25 minutes soft limit
# Large legacy JSON imports override per-task (see tenancy.tasks.run_legacy_import_job)
LEGACY_IMPORT_TASK_TIME_LIMIT = config('LEGACY_IMPORT_TASK_TIME_LIMIT', default=6 * 60 * 60, cast=int)
LEGACY_IMPORT_TASK_SOFT_TIME_LIMIT = config(
    'LEGACY_IMPORT_TASK_SOFT_TIME_LIMIT',
    default=5 * 60 * 60,
    cast=int,
)
CELERY_BROKER_CONNECTION_RETRY_ON_STARTUP = True
CELERY_BEAT_SCHEDULER = 'django_celery_beat.schedulers:DatabaseScheduler'

if ('django_celery_beat', True) not in apps:
    INSTALLED_APPS.append('django_celery_beat')
#### END OF CELERY CONFIGURATION ####

### Cache Configuration (Redis) ###
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.redis.RedisCache',
        'LOCATION': config('REDIS_URL', default=f'{_default_redis}/1'),
    }
} if config('REDIS_URL', default='') else {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
    }
}
#### END OF CACHE CONFIGURATION ####

import warnings

if 'YOUR_SECRET_KEY' in SECRET_KEY:
    warnings.warn('Please set a secure SECRET_KEY in your .env file.', UserWarning)
#### END OF CUSTOM CONFIGURATION SETTINGS ####