# Generated by Django 5.0.6 on 2026-05-21 04:10

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stripe_payments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='userpayment',
            index=models.Index(fields=['stripe_checkout_id'], name='stripe_paym_stripe__4b1926_idx'),
        ),
    ]
