# Generated by Django 5.0.6 on 2026-06-01 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenancy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_ref', models.JSONField(blank=True, default=dict)),
                ('entity', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, default='', max_length=255)),
                ('media', models.CharField(max_length=1000)),
                ('start', models.DateTimeField()),
                ('end', models.DateTimeField()),
                ('action', models.CharField(blank=True, default='', max_length=32)),
                ('target', models.CharField(blank=True, default='', max_length=255)),
                ('advertise_on', models.CharField(max_length=100)),
                ('platform', models.CharField(max_length=16)),
                ('status', models.CharField(default='pending', max_length=16)),
                ('seen', models.IntegerField(default=0)),
                ('clicked', models.IntegerField(default=0)),
                ('island', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.island')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Calendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_ref', models.JSONField(blank=True, default=dict)),
                ('service_type', models.CharField(choices=[('WEEKDAY', 'Weekday'), ('SATURDAY', 'Saturday'), ('SUNDAY', 'Sunday')], max_length=16)),
                ('island', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.island')),
            ],
            options={
                'ordering': ['service_type'],
                'unique_together': {('island', 'service_type')},
            },
        ),
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_ref', models.JSONField(blank=True, default=dict)),
                ('name', models.CharField(max_length=64)),
                ('contact', models.JSONField(blank=True, default=dict)),
                ('island', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.island')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('island', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Line',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_ref', models.JSONField(blank=True, default=dict)),
                ('code', models.CharField(max_length=32)),
                ('display_name', models.CharField(blank=True, default='', max_length=120)),
                ('disabled', models.BooleanField(default=False)),
                ('island', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.island')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='transit.operator')),
            ],
            options={
                'ordering': ['code'],
                'unique_together': {('island', 'code')},
            },
        ),
        migrations.CreateModel(
            name='RouteInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_ref', models.JSONField(blank=True, default=dict)),
                ('text', models.JSONField(blank=True, default=dict)),
                ('source', models.CharField(blank=True, default='', max_length=500)),
                ('company', models.CharField(blank=True, default='', max_length=32)),
                ('start', models.DateTimeField(blank=True, null=True)),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('island', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.island')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_ref', models.JSONField(blank=True, default=dict)),
                ('name', models.CharField(max_length=200)),
                ('cleaned_name', models.CharField(db_index=True, max_length=200)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('island', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.island')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StopGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_ref', models.JSONField(blank=True, default=dict)),
                ('name', models.CharField(max_length=64)),
                ('stop_names', models.JSONField(default=list)),
                ('island', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.island')),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_ref', models.JSONField(blank=True, default=dict)),
                ('headsign', models.CharField(blank=True, default='', max_length=200)),
                ('direction', models.CharField(blank=True, default='', max_length=32)),
                ('likes', models.IntegerField(default=0)),
                ('dislikes', models.IntegerField(default=0)),
                ('source', models.CharField(choices=[('operator', 'Operator timetable'), ('gmaps', 'Google Maps derived')], default='operator', max_length=16)),
                ('calendar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='trips', to='transit.calendar')),
                ('information', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trips', to='transit.routeinfo')),
                ('island', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.island')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='transit.line')),
            ],
        ),
        migrations.CreateModel(
            name='StopTime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_ref', models.JSONField(blank=True, default=dict)),
                ('sequence', models.PositiveIntegerField()),
                ('departure_time', models.TimeField()),
                ('arrival_time', models.TimeField(blank=True, null=True)),
                ('island', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.island')),
                ('stop', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stop_times', to='transit.stop')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stop_times', to='transit.trip')),
            ],
            options={
                'ordering': ['trip', 'sequence'],
            },
        ),
        migrations.CreateModel(
            name='Holiday',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_ref', models.JSONField(blank=True, default=dict)),
                ('date', models.DateField()),
                ('name', models.CharField(max_length=120)),
                ('island', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.island')),
            ],
            options={
                'ordering': ['date'],
                'unique_together': {('island', 'date')},
            },
        ),
        migrations.AddIndex(
            model_name='stop',
            index=models.Index(fields=['island', 'cleaned_name'], name='transit_sto_island__f41895_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='stopgroup',
            unique_together={('island', 'name')},
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['island', 'line', 'calendar'], name='transit_tri_island__945076_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='stoptime',
            unique_together={('trip', 'sequence')},
        ),
    ]
