# Generated by Django 5.0.6 on 2026-06-01 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transit', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='information',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
