# Generated by Django 4.2.29 on 2026-07-03 22:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("tenancy", "0015_appreleaseconfig_in_app_review_enabled"),
        ("transit", "0002_alter_trip_information"),
    ]

    operations = [
        migrations.CreateModel(
            name="AdEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("legacy_ref", models.JSONField(blank=True, default=dict)),
                ("kind", models.CharField(db_index=True, max_length=16)),
                ("platform", models.CharField(blank=True, default="", max_length=16)),
                (
                    "occurred_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "ad",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="transit.ad",
                    ),
                ),
                (
                    "island",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="tenancy.island"
                    ),
                ),
            ],
            options={
                "db_table": "transit_ad_event",
                "indexes": [
                    models.Index(
                        fields=["island", "kind", "occurred_at"],
                        name="transit_ad__island__788dca_idx",
                    ),
                    models.Index(
                        fields=["ad", "kind", "occurred_at"],
                        name="transit_ad__ad_id_a3751a_idx",
                    ),
                ],
            },
        ),
    ]
