# Generated by Django 5.0.6 on 2026-08-14 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('azoresbus', '0001_service_calendar'),
        ('tenancy', '0018_seed_sao_miguel_island'),
        ('transit', '0005_dataset_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='stoptime',
            name='day_offset',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stoptime',
            name='external_stop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stop_times', to='azoresbus.externalstop'),
        ),
        migrations.AlterField(
            model_name='trip',
            name='calendar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trips', to='transit.calendar'),
        ),
        migrations.CreateModel(
            name='ServicePattern',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_ref', models.JSONField(blank=True, default=dict)),
                ('dataset', models.CharField(choices=[('legacy', 'Legacy network'), ('azoresbus', 'AzoresBus 2026')], db_index=True, default='legacy', max_length=16)),
                ('key', models.CharField(db_index=True, max_length=64)),
                ('monday', models.BooleanField(default=False)),
                ('tuesday', models.BooleanField(default=False)),
                ('wednesday', models.BooleanField(default=False)),
                ('thursday', models.BooleanField(default=False)),
                ('friday', models.BooleanField(default=False)),
                ('saturday', models.BooleanField(default=False)),
                ('sunday', models.BooleanField(default=False)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('end_unknown', models.BooleanField(default=False)),
                ('ambiguous_weekdays', models.JSONField(blank=True, default=list)),
                ('confidence', models.CharField(choices=[('sampled', 'Inferred from observed dates'), ('official', 'Published by the operator')], default='sampled', max_length=16)),
                ('derived_from_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_patterns', to='azoresbus.syncrun')),
                ('island', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.island')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceException',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_ref', models.JSONField(blank=True, default=dict)),
                ('date', models.DateField(db_index=True)),
                ('exception_type', models.PositiveSmallIntegerField(choices=[(1, 'Added'), (2, 'Removed')])),
                ('island', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.island')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exceptions', to='transit.servicepattern')),
            ],
        ),
        migrations.AddField(
            model_name='trip',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trips', to='transit.servicepattern'),
        ),
        migrations.AddIndex(
            model_name='trip',
            index=models.Index(fields=['island', 'dataset', 'service'], name='transit_tri_island__d1cd06_idx'),
        ),
        migrations.AddIndex(
            model_name='servicepattern',
            index=models.Index(fields=['island', 'dataset'], name='transit_ser_island__684ccf_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='servicepattern',
            unique_together={('island', 'dataset', 'key')},
        ),
        migrations.AddIndex(
            model_name='serviceexception',
            index=models.Index(fields=['service', 'date'], name='transit_ser_service_97652b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='serviceexception',
            unique_together={('service', 'date')},
        ),
    ]
