# Generated by Django 5.0.6 on 2026-08-24 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenancy", "0020_enable_trails_all_islands"),
        ("transit", "0008_seed_azoresbus_flags"),
    ]

    operations = [
        migrations.CreateModel(
            name="StopAlias",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("legacy_ref", models.JSONField(blank=True, default=dict)),
                (
                    "dataset",
                    models.CharField(
                        choices=[
                            ("legacy", "Legacy network"),
                            ("azoresbus", "AzoresBus 2026"),
                        ],
                        db_index=True,
                        default="legacy",
                        max_length=16,
                    ),
                ),
                ("cleaned_alias", models.CharField(db_index=True, max_length=200)),
                (
                    "island",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="tenancy.island"
                    ),
                ),
                (
                    "stop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="aliases",
                        to="transit.stop",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["island", "dataset", "cleaned_alias"],
                        name="transit_sto_island__11ab96_idx",
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="stopalias",
            constraint=models.UniqueConstraint(
                fields=("island", "dataset", "cleaned_alias"),
                name="uniq_stop_alias_per_dataset",
            ),
        ),
    ]
