# Generated by Django 5.0.6 on 2026-08-24 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenancy", "0020_enable_trails_all_islands"),
        ("transit", "0010_canonicalize_azoresbus_stop_names"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="stop",
            constraint=models.UniqueConstraint(
                condition=models.Q(("dataset", "azoresbus")),
                fields=("island", "dataset", "cleaned_name"),
                name="uniq_azoresbus_stop_cleaned_name",
            ),
        ),
    ]
