# Generated by Django 5.0.6 on 2026-06-01 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request', models.CharField(max_length=100)),
                ('origin', models.CharField(default='', max_length=100)),
                ('destination', models.CharField(default='', max_length=100)),
                ('type_of_day', models.CharField(default='NA', max_length=100)),
                ('time', models.CharField(default='NA', max_length=100)),
                ('platform', models.CharField(default='NA', max_length=100)),
                ('language', models.CharField(default='NA', max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'analytics_stat',
                'indexes': [models.Index(fields=['request', 'timestamp'], name='analytics_s_request_bd821c_idx')],
            },
        ),
    ]
