# Generated by Django 5.0.6 on 2026-06-02 11:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
        ('tenancy', '0003_alter_legacyimportjob_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalyticsEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('legacy_ref', models.JSONField(blank=True, default=dict)),
                ('module', models.CharField(db_index=True, max_length=32)),
                ('event_type', models.CharField(db_index=True, max_length=32)),
                ('properties', models.JSONField(blank=True, default=dict)),
                ('session_hash', models.CharField(blank=True, db_index=True, default='', max_length=64)),
                ('consent_state', models.JSONField(blank=True, default=dict)),
                ('platform', models.CharField(default='web', max_length=16)),
                ('locale', models.CharField(default='pt', max_length=8)),
                ('app_version', models.CharField(blank=True, default='', max_length=32)),
                ('occurred_at', models.DateTimeField(db_index=True)),
                ('island', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tenancy.island')),
            ],
            options={
                'db_table': 'analytics_event',
                'ordering': ['-occurred_at'],
                'indexes': [models.Index(fields=['island', 'module', 'occurred_at'], name='analytics_e_island__17ff2f_idx')],
            },
        ),
    ]
