[pytest]
DJANGO_SETTINGS_MODULE = src.settings
pythonpath = .
testpaths =
    tests
    shared/tests
    app/tests
    blog/tests
    free_tools/tests
    stripe_payments/tests
    legal
python_files = test_*.py tests.py
python_classes = Test* *Tests
python_functions = test_*
