[pytest]
DJANGO_SETTINGS_MODULE = src.settings
pythonpath = .
testpaths =
    tests
    weather/tests
    transit/tests
    azoresbus/tests
    shared/tests
    app/tests
    legal
python_files = test_*.py tests.py
python_classes = Test* *Tests
python_functions = test_*
