# Generated by Django 4.2.29 on 2026-06-02 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenancy", "0005_enable_news_feature_flag"),
    ]

    operations = [
        migrations.CreateModel(
            name="Trail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("legacy_ref", models.JSONField(blank=True, default=dict)),
                ("source_ref", models.CharField(max_length=128)),
                ("name", models.CharField(max_length=200)),
                ("difficulty", models.CharField(blank=True, default="", max_length=32)),
                ("distance_km", models.FloatField(blank=True, null=True)),
                ("geojson", models.JSONField(blank=True, default=dict)),
                (
                    "island",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="tenancy.island"
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
                "unique_together": {("island", "source_ref")},
            },
        ),
        migrations.CreateModel(
            name="TrailStage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("legacy_ref", models.JSONField(blank=True, default=dict)),
                ("name", models.CharField(max_length=200)),
                ("sequence", models.PositiveIntegerField(default=1)),
                ("geojson", models.JSONField(blank=True, default=dict)),
                (
                    "island",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="tenancy.island"
                    ),
                ),
                (
                    "trail",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="stages",
                        to="trails.trail",
                    ),
                ),
            ],
            options={
                "ordering": ["sequence"],
            },
        ),
        migrations.CreateModel(
            name="POI",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("legacy_ref", models.JSONField(blank=True, default=dict)),
                ("name", models.CharField(max_length=200)),
                ("category", models.CharField(blank=True, default="", max_length=64)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                (
                    "island",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="tenancy.island"
                    ),
                ),
            ],
            options={
                "verbose_name": "POI",
                "verbose_name_plural": "POIs",
                "ordering": ["name"],
            },
        ),
    ]
