# Generated by Django 5.0.6 on 2026-06-01 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Island',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('archipelago', models.CharField(default='Azores', max_length=64)),
                ('is_live', models.BooleanField(default=False)),
                ('center_lat', models.FloatField(default=37.7822)),
                ('center_lng', models.FloatField(default=-25.4998)),
                ('radius_km', models.PositiveIntegerField(default=50)),
                ('timezone', models.CharField(default='Atlantic/Azores', max_length=64)),
                ('default_locale', models.CharField(default='pt', max_length=8)),
                ('locales', models.JSONField(default=list)),
                ('theme', models.JSONField(blank=True, default=dict)),
                ('feature_flags', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
