# Generated by Django 5.0.6 on 2026-06-02 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenancy', '0002_legacyimportjob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='legacyimportjob',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
