# Generated by Django 4.2.29 on 2026-06-02 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenancy", "0005_enable_news_feature_flag"),
    ]

    operations = [
        migrations.CreateModel(
            name="SeismicEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("legacy_ref", models.JSONField(blank=True, default=dict)),
                ("emsc_id", models.CharField(max_length=64)),
                ("magnitude", models.FloatField()),
                ("depth_km", models.FloatField(blank=True, null=True)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("occurred_at", models.DateTimeField(db_index=True)),
                ("region", models.CharField(blank=True, default="", max_length=200)),
                (
                    "island",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="tenancy.island"
                    ),
                ),
            ],
            options={
                "ordering": ["-occurred_at"],
                "unique_together": {("island", "emsc_id")},
            },
        ),
        migrations.CreateModel(
            name="FeltReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("legacy_ref", models.JSONField(blank=True, default=dict)),
                ("session_hash", models.CharField(db_index=True, max_length=64)),
                ("intensity", models.PositiveSmallIntegerField()),
                ("latitude", models.FloatField(blank=True, null=True)),
                ("longitude", models.FloatField(blank=True, null=True)),
                ("reported_at", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="felt_reports",
                        to="seismic.seismicevent",
                    ),
                ),
                (
                    "island",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="tenancy.island"
                    ),
                ),
            ],
            options={
                "ordering": ["-reported_at"],
            },
        ),
    ]
