# Generated by Django 5.0.6 on 2026-06-02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("seismic", "0002_periodic_task_sync_events"),
    ]

    operations = [
        migrations.AddField(
            model_name="feltreport",
            name="felt",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="feltreport",
            name="intensity",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
