# Generated by Django 5.0.6 on 2026-06-02 15:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenancy", "0008_enable_marketplace_feature_flag"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrafficCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("legacy_ref", models.JSONField(blank=True, default=dict)),
                ("name", models.CharField(max_length=80)),
                ("slug", models.SlugField(max_length=80)),
                ("icon", models.CharField(blank=True, default="", max_length=64)),
                (
                    "default_ttl_minutes",
                    models.PositiveIntegerField(
                        default=120,
                        help_text="How long a fresh report of this category stays active.",
                    ),
                ),
                (
                    "is_schedulable",
                    models.BooleanField(
                        default=False,
                        help_text="Allow pre-announced reports with a future active_from (e.g. radar).",
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                (
                    "island",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="tenancy.island"
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Traffic categories",
                "ordering": ["order", "name"],
                "unique_together": {("island", "slug")},
            },
        ),
        migrations.CreateModel(
            name="TrafficReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("legacy_ref", models.JSONField(blank=True, default=dict)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("scheduled", "Scheduled"),
                            ("expired", "Expired"),
                            ("removed", "Removed"),
                        ],
                        db_index=True,
                        default="active",
                        max_length=16,
                    ),
                ),
                (
                    "created_by_session_hash",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
                ("description", models.TextField(blank=True, default="")),
                ("road", models.CharField(blank=True, default="", max_length=160)),
                ("active_from", models.DateTimeField(blank=True, null=True)),
                ("active_until", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(db_index=True)),
                ("confirm_count", models.PositiveIntegerField(default=0)),
                ("deny_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="reports",
                        to="traffic.trafficcategory",
                    ),
                ),
                (
                    "island",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="tenancy.island"
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TrafficConfirmation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("legacy_ref", models.JSONField(blank=True, default=dict)),
                ("session_hash", models.CharField(db_index=True, max_length=64)),
                (
                    "vote",
                    models.CharField(
                        choices=[("still_there", "Still there"), ("gone", "Gone")],
                        max_length=16,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "island",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="tenancy.island"
                    ),
                ),
                (
                    "report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="confirmations",
                        to="traffic.trafficreport",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="trafficreport",
            index=models.Index(
                fields=["island", "status", "expires_at"],
                name="traffic_tra_island__d9c8a2_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="trafficconfirmation",
            unique_together={("report", "session_hash")},
        ),
    ]
